%
%   write_RAPID_v001
%
function status = write_RAPID_v001()



%




RAPID_dir    = 'Trajectories_dot_h\';

RAPID_name = trajectoryString;

dot_h_file_name = [ RAPID_dir RAPID_name '.h' ];

fh = fopen( dot_h_file_name ,'w');

author = 'Adonis Canada, Priyanshu Agrawal, Baris Sengezen';
time = datestr(now, 'HH:MM');
date_today = date;

formatSpec_title  = ['// THIS IS AUTOGENERATED CODE FOR .H FILES FOR TRAJECTORIES WRITTEN IN MATLAB' '\n']; 
formatSpec_header = ['// ' date_today ' at ' time '   Auto-generated by Matlab by ' author '\n'];
fprintf(fh, formatSpec_title);
fprintf(fh, formatSpec_header);



fprintf(fh,  '#include  "../ProfileData.h" \n' );

formatSpec = [ 'const double t_final_' RAPID_name ' = %10.2f;\n' ];

fprintf(fh,formatSpec,t_final);

formatSpec = [ 'const int i_final_' RAPID_name ' = %10.0f;\n' ];

fprintf(fh,formatSpec,i_final);

formatSpec = [ 'const double t_auto_end_' RAPID_name ' = %10.2f;\n' ];

fprintf(fh,formatSpec,t_auto_end);

formatSpec = [ 'const int i_auto_end_' RAPID_name ' = %10.0f;\n' ];

fprintf(fh,formatSpec,i_auto_end);

%   Right motor code

formatSpec = [ 'const ProfileData AutoMove_' RAPID_name '_R = {{\n' ];

fprintf(fh,formatSpec);

formatSpec = '{ %13.6f , %13.6f , %13.6f },\n';

for i=1:N
    
    if i == N
        
        formatSpec = '{ %13.6f , %13.6f , %13.6f }\n'  ;
        
    end
    
    fprintf( fh, formatSpec, [enc_R(i), enc_per_100ms_R(i), Robot.Ts*1000]);
    
end

formatSpec = '}};\n';

fprintf(fh,formatSpec);

%   Left motor code

formatSpec = [ 'const ProfileData AutoMove_' RAPID_name '_L = {{\n'];

fprintf(fh,formatSpec);

formatSpec = '{ %13.6f , %13.6f , %13.6f },\n';

for i=1:N
    
    if i == N
        
        formatSpec = '{ %13.6f , %13.6f , %13.6f }\n'  ;
        
    end
    
    fprintf( fh, formatSpec, [enc_L(i), enc_per_100ms_L(i), Robot.Ts*1000]);
    
end

formatSpec = '}};\n';

fprintf(fh,formatSpec);

status = ~fclose(fh);

if status,
    
    disp([ dot_h_file_name '        written successfully...' ]);
    
else
    
    disp([ dot_h_file_name '        ERROR!' ]);
    
end
